name: collect
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge

dependencies:
    - numpy==1.16.1
    - python==3.7
#    - menpo::opencv
    - opencv
#    - defaults::libprotobuf 
#    - defaults::protobuf     
    - matplotlib
    - pyyaml
    - pyautogui
    - pip:
        - pynput
